# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  acerola_game_jam_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  acerola_game_jam_config = debug_x86

else ifeq ($(config),debug_arm64)
  raylib_config = debug_arm64
  acerola_game_jam_config = debug_arm64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  acerola_game_jam_config = release_x64

else ifeq ($(config),release_x86)
  raylib_config = release_x86
  acerola_game_jam_config = release_x86

else ifeq ($(config),release_arm64)
  raylib_config = release_arm64
  acerola_game_jam_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib acerola-game-jam

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C build -f raylib.make config=$(raylib_config)
endif

acerola-game-jam: raylib
ifneq (,$(acerola_game_jam_config))
	@echo "==== Building acerola-game-jam ($(acerola_game_jam_config)) ===="
	@${MAKE} --no-print-directory -C build -f acerola-game-jam.make config=$(acerola_game_jam_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f raylib.make clean
	@${MAKE} --no-print-directory -C build -f acerola-game-jam.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   acerola-game-jam"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"